#Auth Endpoints
POST http://locahost:8080/login HTTP/1.1
Content-Type: application/json

{
   "email": "theBatman@test.com",
   "password": "bestSuperNum1"
}

###

PUT http://localhost:8080/signup HTTP/1.1
Content-Type: application/json

{
   "firstName": "Bruce",
   "lastName": "Wayne",
   "email": "theBatman@test.com",
   "password": "bestSuperNum1",
}

###

#Recipe Endpoints
POST http://localhost:8080/recipe HTTP/1.1
Content-Type: application/json

{
   "title": "This is from test.http",
   "userId": "62316881efcc971eb862e952",//Add existing Id,
   "description": "Vegetable Soup",
   "imageUrl" : "dummy-image.jpg",
   //MODIFIED: Ingredients is now a String instead of list of objects
   "ingredients": "1 Onion\n3 Garlic Cloves\n1 Can Diced Tomatoes\n1 Can Chicken Stock", 
   "instructions": "Put all ingredients in a pot. Simmer for 20 mins"
}

###

PUT http://localhost:8080/recipes/[recipeId] HTTP/1.1
Content-Type: application/json

{
   "title": "This is from test.http",
   "userId": "62316881efcc971eb862e952",//Add existing Id,
   "description": "Vegetable Soup",
   "imageUrl" : "dummy-image.jpg",
   //MODIFIED: Ingredients is now a String instead of list of objects
   "ingredients": "1 Onion\n3 Garlic Cloves\n1 Can Diced Tomatoes\n1 Can Chicken Stock", 
   "instructions": "These are the Edited Instructions"
}

###

DELETE http://localhost:8080/recipes/[recipeId] HTTP/1.1
Content-Type: application/json

###

//Returns all json recipe data
GET http://localhost:8080/recipes HTTP/1.1
Content-Type: application/json

###

//Returns json data for a specific recipe
//add recipeId in bellow http to test
GET http://localhost:8080/recipes/[recipeId] HTTP/1.1
Content-Type: application/json

###

